name: workflow name

on:
  push:
    branches: [main]

permissions:
  contents: read
jobs:
  get-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.print.outputs.affected }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat ./setting.json
          key=$(cat ./setting.json | jq -r .title)
          echo "KEY=${key}" >> "$GITHUB_ENV"
        id: print

  do-each:
    needs: [get-targets]
    runs-on: ubuntu-latest
    strategy: ${{fromJson(needs.get-targets.outputs.targets)}}
    concurrency: package-${{matrix.key1}}
    steps:
      - run: echo ${{matrix.key1}}
