name: workflow name

on:
  push:
    branches: [main]

permissions:
  contents: read
jobs:
  get-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.print.outputs.affected }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          content=`cat ./setting.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo $content
          echo "key=$content"  >> "$GITHUB_OUTPUT"
        id: print

  do-each:
    needs: [get-targets]
    runs-on: ubuntu-latest
    strategy: ${{fromJson(needs.get-targets.outputs.targets)}}
    concurrency: package-${{matrix.key1}}
    steps:
      - run: echo ${{matrix.key1}}
