name: workflow name

on:
  push:
    branches: [main]

permissions:
  contents: read
jobs:
  get-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.print.outputs.key }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat ./setting.json
          key=$(cat ./setting.json)
          echo "KEY=${key}" >> $GITHUB_OUTPUT
        id: print

  do-each:
    needs: [get-targets]
    runs-on: ubuntu-latest
    # strategy: ${{fromJson(needs.get-targets.outputs.targets)}}
    # concurrency: package-${{matrix}}
    steps:
      - run: echo ${{fromJson(needs.get-targets.outputs.targets)}}
